In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
y=df.drop(labels="species",axis=1)
y

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [4]:
x=df[["sepal_length","sepal_width","petal_length","petal_width"]]


In [5]:
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [7]:
x_train.shape

(105, 4)

In [8]:
len(x_test)

45

In [9]:
x_train

sepal_length  sepal_width  petal_length  petal_width
35            5.0          3.2           1.2          0.2
126           6.2          2.8           4.8          1.8
104           6.5          3.0           5.8          2.2
148           6.2          3.4           5.4          2.3
122           7.7          2.8           6.7          2.0
..            ...          ...           ...          ...
8             4.4          2.9           1.4          0.2
120           6.9          3.2           5.7          2.3
135           7.7          3.0           6.1          2.3
15            5.7          4.4           1.5          0.4
66            5.6          3.0           4.5          1.5

[105 rows x 4 columns]

In [10]:
from sklearn.linear_model import LinearRegression
regr=LinearRegression()

In [11]:
regr.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred=regr.predict(x_test)

In [13]:
y_pred

array([[5.4, 3.7, 1.5, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5.4, 3.9, 1.3, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [7.2, 3. , 5.8, 1.6],
       [5.2, 2.7, 3.9, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.8, 2.7, 3.9, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [5.8, 2.6, 4. , 1.2],
       [7. , 3.2, 4.7, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.2, 4.5, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 5. , 1.5],
       [5.1, 3.8, 1.9, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [4.6, 3.1, 1.5, 0.2],
       [5.6, 3. , 4.1, 1.3],
       [6. , 2.2, 4. , 1. ],
       [4.6, 3.2, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.5, 2

In [14]:
from sklearn import metrics
print("mean squared error:",metrics.mean_squared_error(y_test,y_pred))

mean squared error: 5.451933186182189e-31


In [15]:
score=regr.score(y_test,y_pred)
score

1.0

In [16]:
print(regr.intercept_)

[ 2.66453526e-15  1.77635684e-15 -2.22044605e-15  2.22044605e-16]


In [17]:
print(regr.coef_)

[[ 1.00000000e+00 -2.16183744e-16 -1.36020140e-16  4.71144485e-17]
 [-1.22627770e-16  1.00000000e+00 -4.14021115e-17 -2.02292536e-17]
 [ 1.28182741e-16 -2.22044605e-16  1.00000000e+00  2.21461793e-16]
 [ 3.09110759e-16 -5.55111512e-16 -1.76196175e-16  1.00000000e+00]]


In [20]:
VisualAnalysis(df)

NameError: name 'VisualAnalysis' is not defined

In [ ]:
!pip install pandas_visua